### ISSUE TITLE
crash on node 4.4.3

### ISSUE THREAD

**Issue by god-of-pmi** [guyonroche/promish#2]
since 5.0.3 version crash on node 4.4.3 with 

> Block-scoped declarations (let, const, function, class) not yet supported outside strict mode 

It crash because `'use strict';` was deleted from ../lib/promish-class

why did you do it?

**Comment by antonshokut** [comment]
Have the same issue. Node version 4.4.4.
@guyonroche  could you fix it please?

**Comment by TimTilroy** [comment]
Same issue here on Node 4.5. Crashes on the strict mode line that is removed.

**Comment by sudhashree93** [comment]
Facing the same issue. Is there any way to fix this ?

**Comment by dreaganluna** [comment]
Could you please take a look at this? I have to add that line back manually now with every deployment..

**Comment by guyonroche** [comment]
Apologies, only just checked in today - I've added the 'use strict' line
